config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  
  resources :users, only: [:index, :show, :new, :create] do
    member do
      get :followings
      get :followers
      get :likes
    end
    collection do
      get :search
    end
  end
    
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]

    # member do #idがいる時
    #   get 'extendshow'
    # end
    
    # collection do #idがいらない
    #   get 'edit'
    #   patch 'update'
    #   put   'update'
    #   delete 'destroy'
      
    
end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email.downcase!} #保存する前に全ての文字を小文字に変換
  validates :name, presence: true, length: {maximum: 50}
  validates :email, presence: true, length: {maximum: 255},
            format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, #emailを表す正規表現
            uniqueness: {case_sensitive: false} #大文字と小文字の区別をせず同じものと見なす
  
  has_secure_password
  
  has_many :microposts
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverses_of_relationship, source: :user
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end
  
  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end
  
  def following?(other_user)
    self.followings.include?(other_user)
  end
  
  def feed_microposts
    Micropost.where(user_id: self.following_ids + [self.id])
  end
  
  has_many :favorites
  has_many :favos, through: :favorites, source: :micropost
  # has_many :reverses_of_favorite, class_name: 'Favorite', foreign_key: 'micropost_id'
  # has_many :favoers, through: :reverses_of_favorite, source: :user
  
  def like(other_micropost)
   # unless self == other_micropost #micropost.user_idを参照させる？
    self.favorites.find_or_create_by(micropost_id: other_micropost.id)
   #end
  end
  
  def unlike(other_micropost)
    favorite = self.favorites.find_by(micropost_id: other_micropost.id) #other_micropostが引数だから検索もother_micropost
    favorite.destroy if favorite
  end
  
  def favos?(other_micropost) #has_manyで設定したfavosがあるかどうか
    self.favos.include?(other_micropost)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :followings, :followers, :link]
  
  def index
    @users = User.all.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.order('created_at DESC').page(params[:page])
    @micropost = Micropost.find_by(params[:micropost_id])
    counts(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'ユーザーの新規登録が出来ました'
      redirect_to @user
    else
      flash.now[:danger] = '登録に失敗しました'
      render :new
    end
  end
  
  def followings
    @user = User.find(params[:id])
    @followings = @user.followings.page(params[:page])
    counts(@user)
  end
  
  def followers
    @user = User.find(params[:id])
    @followers = @user.followers.page(params[:page])
    counts(@user)
  end
    
  def edit
    # @user = User.find(params[:id])
    @user = current_user
  end
  
  def update
    @user = current_user
    if @user.update(user_params)
      flash[:success] = "更新しました"
      redirect_to @user
    else
      flash[:error] = "更新できませんでした"
      render :edit
    end
  end
  
  def destroy
    @user = current_user
    @user.destroy
    
    flash[:success] = 'アカウントを削除しました'
    redirect_to root_url
  end
  
  def likes
    #binding.pry
    @user = User.find(params[:id])
    #@micropost = Micropost.find(params[:id]) #いらない？
    @favos = @user.favos.page(params[:page]) #user.id ,favorites => micropost.id micropostテーブルの中身
    counts(@user)
  end
    


private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options ={size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="media-list">
    <% users.each do |user| %>
    <li class="media">
      <div class="media-left">
        <img class="media-object img-rounded" src="<%= gravatar_url(user, {size:50}) %>" alt="">
      </div>
      <div class="media-body">
        <div>
          <%= user.name %>
        </div>
        <div>
          <p><%= link_to 'プロフィール', user_path(user) %></p>
        </div>
      </div>
    </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/edit.html.erb
<div class="text-center">
  <h1>プロフィール変更</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    
      <div class="form-group">
        <%= f.label :name, '名前' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      

      <%= f.submit '変更', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/favarite.html.erb
<div class="row">
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        <img class="media-object img-rounded img-responsive" src="<% gravatar_url(@user, {size: 500}) %>" alt="">
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>Microposts<span class="badge"><%= @count_microposts %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followings_user_path(@user)) %>"><%= link_to followings_user_path(@user) do %>フォロー<span class="badge"><%= @count_followings %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followers_user_path(@user)) %>"><%= link_to followers_user_path(@user) do %>フォロワー<span class="badge"><%= @count_followers %></span><% end %></li>
      <li class="<%= 'active' if current_page?(favos_user_path(@user)) %>"><%= link_to favos_user_path(@user) do %>お気に入り<span class="badge"><%= @count_favos %></span><% end %></li>
    </ul>
    <%= render 'users', users: @favos %>
  </div>
</div>

app/views/users/followers.html.erb
<div class="row">
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        <img class="media-object img-rounded img-responsive" src="<%= gravatar_url(@user, {size: 500}) %>" alt="">
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>Microposts<span class="badge"><%= @count_microposts %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followings_user_path(@user)) %>"><%= link_to followings_user_path(@user) do %>フォロー<span class="badge"><%= @count_followings %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followers_user_path(@user)) %>"><%= link_to followers_user_path(@user) do %>フォロワー<span class="badge"><%= @count_followers %></span><% end %></li>
      <li class="<%= 'active' if current_page?(likes_user_path(@user)) %>"><%= link_to likes_user_path(@user) do %>お気に入り<span class="badge"><%= @count_favos %></span><% end %></li>
    </ul>
    <%= render 'users', users: @followers %>
  </div>
</div>

app/views/users/followings.html.erb
<div class="row">
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        <img class="media-object img-rounded img-responsive" src="<% gravatar_url(@user, {size: 500}) %>" alt="">
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>Microposts<span class="badge"><%= @count_microposts %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followings_user_path(@user)) %>"><%= link_to followings_user_path(@user) do %>フォロー<span class="badge"><%= @count_followings %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followers_user_path(@user)) %>"><%= link_to followers_user_path(@user) do %>フォロワー<span class="badge"><%= @count_followers %></span><% end %></li>
    </ul>
    <%= render 'users', users: @followings %>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/likes.html.erb
<div class="row">
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        <img class="media-object img-rounded img-responsive" src="<%= gravatar_url(@user, {size: 500}) %>" alt="">
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>Microposts<span class="badge"><%= @count_microposts %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followings_user_path(@user)) %>"><%= link_to followings_user_path(@user) do %>フォロー<span class="badge"><%= @count_followings %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followers_user_path(@user)) %>"><%= link_to followers_user_path(@user) do %>フォロワー<span class="badge"><%= @count_followers %></span><% end %></li>
      <li class="<%= 'active' if current_page?(likes_user_path(@user)) %>"><%= link_to likes_user_path(@user) do %>お気に入り<span class="badge"><%= @count_favos %></span><% end %></li>
    </ul>
    <%= render 'microposts/microposts', microposts: @favos %>
  </div>
</div>

app/views/users/new.html.erb
<div class="text-center">
  <h1>新規登録</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    
      <div class="form-group">
        <%= f.label :name, '名前' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.text_field :email, class: 'form-control' %>
      </div>
          
      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
          
      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード確認' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      
      <%= f.submit '登録', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        <img class="media-object img-rounded img-responsive" src="<%= gravatar_url(@user, {size: 500}) %>" alt="">
        <%#= link_to 'アカウントの編集', edit_users_path %>
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %> Microposts <span class="badge"><%= @count_microposts %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followings_user_path(@user)) %>"><%= link_to followings_user_path(@user) do %>フォロー<span class="badge"><%= @count_followings %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followers_user_path(@user)) %>"><%= link_to followers_user_path(@user) do %>フォロワー<span class="badge"><%= @count_followers %></span><% end %></li>
      <li class="<%= 'active' if current_page?(likes_user_path(@user)) %>"><%= link_to likes_user_path(@user) do %>お気に入り<span class="badge"><%= @count_favos %></span><% end %></li>
    </ul>
    <%= render 'microposts/microposts', microposts: @microposts %>
  </div>
</div>